# Dependencies
highlighter:      false


# Permalinks
permalink:

# Source
source:           DIR

# Settings
destination:      DIR
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             TTAGIT blog
url:              http://ttagit.com/blog

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false


# Links
expo_repo:        https://github.com/ttagit/blog
expo_new_issue:

docs:             http://getbootstrap.com
blog:             http://blog.getbootstrap.com
