# Dependencies
highlighter:      false


# Permalinks
permalink:        pretty


# Settings
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             TTAGIT blog
url:              http://ttagit.com/blog


# Links
expo_repo:        https://github.com/ttagit/blog
expo_new_issue:

docs:             http://getbootstrap.com
blog:             http://blog.getbootstrap.com
