# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
relative_permalinks:

# Setup
title:            TTAGIT
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ttagit.com/blog/
baseurl:          http://ttagit.com/blog/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          3.0

github:
  repo:           https://github.com/poole/hyde
